// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DetailsToggleController from "./details_toggle_controller"
application.register("details-toggle", DetailsToggleController)

import LinkBuilderController from "./link_builder_controller"
application.register("link-builder", LinkBuilderController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PairRequestsFormController from "./pair_requests_form_controller"
application.register("pair-requests-form", PairRequestsFormController)

import SelectController from "./select_controller"
application.register("select", SelectController)
