// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import PairRequestsFormController from './pair_requests_form_controller';

import LinkBuilderController from './link_builder_controller';

application.register('pair-requests-form', PairRequestsFormController);
application.register('link-builder', LinkBuilderController);
